name: Reset control labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - "main"

permissions:
  issues: write
  pull-requests: write

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Remove run core label
        run: |
          curl \
            -X DELETE \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ github.token }}' \
            'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/run%20core'

      - name: Remove run integration label
        run: |
          curl \
            -X DELETE \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ github.token }}' \
            'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/run%20integration'


